### ISSUE TITLE
[Feature Request]: editable preferences via typing 

### ISSUE THREAD

**Issue by mande01** [jithware/brethap#106]
Can the preferences be editable by selecting the number and editing with a calculator view.

Makes it easier for those with shaky hands.

**Comment by jithware** [comment]
One way to get more "leverage" in adjusting preferences is to rotate your phone into landscape mode. This creates longer sliders for adjustment. 

Please include a wireframe on how you would like this feature to look. Here is how to include wireframes into Brethap: https://github.com/jithware/brethap/discussions/77. If enough other users give this feature a thumbs up, it can be looked into implementing.
