### ISSUE TITLE
[Feature Request]: increase the exhale max time

### ISSUE THREAD

**Issue by happysalada** [jithware/brethap#108]
**Is your feature request related to a problem? Please describe.**
The maximum exhale time is 15s, enabling it to go to 30s would be amazing.
You can increase the time by adding hold and exhale , but it adds vibration which are distracting.

**Describe the solution you'd like**
Enable max exhale time to be 30s

**Describe alternatives you've considered**

**Additional context**
happy to discuss if you need more info !

**Comment by jithware** [comment]
Done! Will be available in release >= 1.7.24+122

**Comment by happysalada** [comment]
Youre amazing !
