### ISSUE TITLE
[Feature Request]: Ignore Audio focus

### ISSUE THREAD

**Issue by Laserlicht** [jithware/brethap#111]
**Is your feature request related to a problem? Please describe.**
It's not possible to play music with an external app in the background. As soon as brethap plays any sound the music app stops (Samsung S23, Android 14).

**Describe the solution you'd like**
Option to ignore audio focus. For example the app "Metronome Beats" from playstore has this option and it's working after enabling (without it's the same problem).

**Comment by jithware** [comment]
Unfortunately I am not aware of any method to enable this within flutter's audio playing capabilities. A possible workaround when playing background audio in another app is to disable audio in brethap by selecting "None" in the Preferences for inhale and exhale and using vibration instead.

**Comment by Laserlicht** [comment]
I've absolutly no expirience in flutter.

But isn't it possible to use this library? https://pub.dev/packages/audio_session

**Comment by Laserlicht** [comment]
Found a solution for me: On samsung devices there is an app "sound assistent" where you can enable this functionality for special apps.
