### ISSUE TITLE
[Bug]: Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [jithware/brethap#112]
Try to reduce the size (dimensions) of monochrome icon it looks creepy and weird

**Comment by jithware** [comment]
Please provide more [detail](https://github.com/jithware/brethap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) including a screenshot.

**Comment by saltsoftdrink** [comment]
> Please provide more [detail](https://github.com/jithware/brethap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) including a screenshot.

https://ibb.co/F6wg0hY - image

Every icon looks good but not the "B" one

**Comment by jithware** [comment]
When submitting bug reports, please fill out **all** [details](https://github.com/jithware/brethap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) in the report. When submitting screenshots, please [attach](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) the screenshot file to the report.

**Smartphone (please complete the following information):**
 - Device:
 - OS: 
 - Brethap Version:

**Comment by saltsoftdrink** [comment]
> When submitting bug reports, please fill out **all** [details](https://github.com/jithware/brethap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) in the report. When submitting screenshots, please [attach](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) the screenshot file to the report.
> 
> **Smartphone (please complete the following information):**
>  - Device:
>  - OS: 
>  - Brethap Version: 
> 
> 

Device - Relame 9 Pro
Os - Android 13
App Version - 1.7.24

**Comment by jithware** [comment]
>  please [attach](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) the screenshot file to the report.

**Comment by saltsoftdrink** [comment]
> > please [attach](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) the screenshot file to the report.


Already uploaded -


https://ibb.co/F6wg0hY

**Comment by jithware** [comment]
To attach a file to an issue or pull request conversation, drag and drop it into the comment box. Alternatively, you can click  in the formatting bar above the comment box to browse, select, and add a file from your computer.
