### ISSUE TITLE
Suggestion: longer breathe time

### ISSUE THREAD

**Issue by One111** [jithware/brethap#19]
Hi! 
Please, expand maximum inhale and exhale time up to 30 seconds or maybe more.

I can comfortly breathe by 15 seconds, but my lungs actualy not so big and I not trained. I guess some people will need bigger intervals for their breath.

I realy love the app an I found it very usefull. Thenks a lot!

**Comment by jithware** [comment]
In release >= 1.2.1+23

Increased maximum total inhale+exhale time to 30 seconds.
