### ISSUE TITLE
Show the presets a name

### ISSUE THREAD

**Issue by gpol3000** [jithware/brethap#24]
Thanks for this app! It's great.

A small feature request. At the bottom of the settings, you can choose 1, 2, 3, 4 etc... It would be handy to enter a name or description for these different settings, so you can easily recognise them.

**Comment by jithware** [comment]
In release >= 1.4.0+26

Note when a new preference is added to the app, the previous saved preferences will be reset. Minor updates to the app result in new preferences for that version. For example 1.3.x -> 1.4.x

New preferences screen:

![preferences](https://github.com/jithware/brethap/raw/e4ef17ae6747af2239010dc534b5586282cee6e3/screenshots/android/preferences.png)
