### ISSUE TITLE
consider 4-part breath settings

### ISSUE THREAD

**Issue by wolftune** [jithware/brethap#3]
ideally length settings could be chosen for inhale, hold, exhale, hold. That's more flexible and used in various exercises.

**Comment by jithware** [comment]
In release >= `1.1.0+21`

Added new functionality and preferences for inhale, hold, exhale, hold.

Changes to storage format require overwriting version 1.0.x sessions and preferences.

Preferences screen below (screen is scrollable):

![prefences](https://raw.githubusercontent.com/jithware/brethap/master/screenshots/android/preferences.png)

**Comment by wolftune** [comment]
Awesome!
