### ISSUE TITLE
Use heart rate info

### ISSUE THREAD

**Issue by PanderMusubi** [jithware/brethap#30]
Implement functionality that uses heart rate (coherence) information from wearables such as watches or heart rate bands.

See also https://play.google.com/store/apps/details?id=uk.co.jatra.inout and https://play.google.com/store/apps/details?id=it.softarea.heartrate

**Comment by jithware** [comment]
Currently the only permission needed is "control vibration". By adding this feature, it would introduce more required permissions, making the app more intrusive to the user. Would like to keep the app as simple as possible, without a lot of added permission requirements. A quick search of https://play.google.com/store/search?q=meditation&c=apps and you can see most meditation apps require several permissions to run.

However if there is enough significant interest in this, it can be investigated further. Please thumbs up this feature if you are interested.

**Comment by PanderMusubi** [comment]
This issue is still relevant.

**Comment by PanderMusubi** [comment]
In the source code of the app RunnerUp is a test signal available for heart rate.

**Comment by PanderMusubi** [comment]
I don't find the stale bot very useful

**Comment by PanderMusubi** [comment]
Ping

**Comment by PanderMusubi** [comment]
- Carlyle HR 0320
- Tacx HRB  08248

**Comment by jithware** [comment]
> * Carlyle HR 0320 
> * Tacx HRB  08248

Did a quick google search and looks like these items combined are over $1000. Not likely to get support from the community to purchase these devices for testing. If other people express interest in these or other devices, will reopen.

**Comment by jithware** [comment]
Now supports heart rate for Wear OS devices. See [Brethap Wear](https://github.com/jithware/brethap_wear#brethap-wear).

**Comment by PanderMusubi** [comment]
What are the requirements?  I have Wear OS 2 but get.this error on the Play website

This app is not available for any of your devices

And it is mot.listed on the Play app.

**Comment by jithware** [comment]
Brethap on Google Play is only available in countries where the primary language is implemented in the app. For information on how to add a language, see https://github.com/jithware/brethap/discussions/52

**Comment by PanderMusubi** [comment]
Added Dutch translation in https://github.com/jithware/brethap/pull/79

**Comment by jithware** [comment]
Thanks @PanderMusubi for the translations!

Heart rate available in Wear OS release >= 1.0.4+71 to the Netherlands on [Google Play](https://play.google.com/store/apps/details?id=com.jithware.brethap&hl=nl)
