### ISSUE TITLE
light on dark would be better

### ISSUE THREAD

**Issue by wolftune** [jithware/brethap#44]
All the dark-theme stuff in general is lighter figure on darker ground (e.g. white text on dark background). So, brethap dark mode should use a lighter circle with a darker (blacker) background instead of a lighter-grey background and darker-grey circle.

**Comment by jithware** [comment]
Behavior of [ThemeData.dark](https://api.flutter.dev/flutter/material/ThemeData/ThemeData.dark.html) (default dark theme in flutter). https://github.com/jithware/brethap/blob/63b9d3ad9f333ddd3c7c59ce16d5b90e2518fc11/lib/main.dart#L97
