### ISSUE TITLE
Audio for breath hold

### ISSUE THREAD

**Issue by geofinder** [jithware/brethap#45]
Could you please add option to choose audio tone when changing state from inhale to hold? Thank you.

**Comment by jithware** [comment]
Depends on https://github.com/jithware/brethap/issues/46

**Comment by jithware** [comment]
@actuallyhuman would you mind providing the German translations for the following:

https://github.com/jithware/brethap/blob/f50e910259f8a57741cd2298faded89faf04d8c3/lib/l10n/app_de.arb#L11

and

https://github.com/jithware/brethap/blob/f50e910259f8a57741cd2298faded89faf04d8c3/lib/l10n/app_de.arb#L13

**Comment by actuallyhuman** [comment]
> @actuallyhuman would you mind providing the German translations for the following:

Sure. Created a pull request #47.

**Comment by jithware** [comment]
> No problem. Created a pull request #47.

Thank you!

In release >= 1.6.0+36
