### ISSUE TITLE
Wrong localization language

### ISSUE THREAD

**Issue by Giannous** [jithware/brethap#55]
**Expected behavior**
Phone language set to italian, but application language is set to german instead of english.

**Smartphone**
 - Device: Poco F3
 - OS: MIUI 12.5.6

**Comment by jithware** [comment]
@Giannous can you please post a screenshot of your language settings like pictured below?

For a demo of language settings see: https://youtu.be/f4MA2YhBVOA

![55](https://user-images.githubusercontent.com/30555367/188498866-846ecf61-54e7-4a88-b094-fd41e1c4971d.png)

**Comment by Giannous** [comment]
On Miui 12 i can only chose one language like in the image.
![Screenshot_2022-09-05-20-21-45-555_com.android.settings.jpg](https://user-images.githubusercontent.com/26120377/188500128-3bc3f97c-c493-4989-a916-a7dfbcde9d8d.jpg)

**Comment by jithware** [comment]
Hmmm, ok. I don't think I will be able to reproduce the issue. Perhaps a solution would be to provide Italian translations for the app.  Would you be willing to do this by following the guide here: https://github.com/jithware/brethap/discussions/52

**Comment by Giannous** [comment]
> Hmmm, ok. I don't think I will be able to reproduce the issue. Perhaps a solution would be to provide Italian translations for the app.  Would you be willing to do this by following the guide here: https://github.com/jithware/brethap/discussions/52

Yeah, i'll try to do it.

**Comment by jithware** [comment]
> Yeah, i'll try to do it.

Thank you!

In release >= 1.7.0+46. Should be available on [Google Play](https://play.google.com/store/apps/details?id=com.jithware.brethap&hl=it_IT) in a few days and [F-Droid](https://f-droid.org/it/packages/com.jithware.brethap/) in a week or so.

**Comment by Giannous** [comment]
> > Yeah, i'll try to do it.
> 
> Thank you!
> 
> In release >= 1.7.0+46. Should be available on [Google Play](https://play.google.com/store/apps/details?id=com.jithware.brethap&hl=it_IT) in a few days and [F-Droid](https://f-droid.org/it/packages/com.jithware.brethap/) in a week or so.
> 
> 

No problem, happy to help!

**Comment by jithware** [comment]
@Giannous looks like it is available on Google Play, but still not on F-Droid. If you have it installed from Google Play, would you mind updating the app to 1.7.0+46 and verifying that you now see Italian translations and not German ones? You can double check which version you have from Menu->About Brethap

**Comment by Giannous** [comment]
> @Giannous looks like it is available on Google Play, but still not on F-Droid. If you have it installed from Google Play, would you mind updating the app to 1.7.0+46 and verifying that you now see Italian translations and not German ones? You can double check which version you have from Menu->About Brethap

I tried the play store version and now italian is shown instead of german.

**Comment by jithware** [comment]
> I tried the play store version and now italian is shown instead of german.

Grazie!

**Comment by vjrj** [comment]
I installed the last version from fdroid and it's in German in my side, instead of Spanish or English. The GitHub web page is in German too. Maybe a language selector in settings is a better option. Thanks

**Comment by gargamel17** [comment]
> I installed the last version from fdroid and it's in German in my side, instead of Spanish or English. The GitHub web page is in German too. Maybe a language selector in settings is a better option. Thanks

Same problem

**Comment by jithware** [comment]
Please submit a new bug report using the [bug report template](https://github.com/jithware/brethap/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBug%5D%3A+) and include all screenshots.
