### ISSUE TITLE
Custom inhale and exhale sounds 

### ISSUE THREAD

**Issue by rorar** [jithware/brethap#57]
At the moment 4 tones are available.
To be honest these tones aren't calming me...
Therefore it would be cool to add own sounds from the media library 
(like real breathing inhale / exhale sounds, a gong, a singing bowl sound,... you name it)

**Comment by jithware** [comment]
This would require additional permissions to Brethap. I would like permissions as minimal as possible (currently only three), as well as Preference UI/storage modifications. 

Instead, I would definitely support adding a few new audio assets that are more calming. If you could provide audio that meets the following:
- "open source" and DRM free
- *.oga format
- original work created by you or other with credit given to source

Put the files in https://github.com/jithware/brethap/tree/master/audio and submit a pull request. I will then add those to the app.
