### ISSUE TITLE
Background noises and sounds 

### ISSUE THREAD

**Issue by rorar** [jithware/brethap#58]
To get calm faster, relaxing noises and sounds can help. (for me, sounds of the woods and binaural beats) 

It would be great to have the option 
- to pick a sound file from the media library or 
- paste in a YouTube link and play the audio while an breath exercise is going on.

Add-ons:
- a fade-in and fade-out of the audio volume at the beginning and ending of an exercise
- set the start (and endpoint for a loop) of ab an audio track
- create a play list of audio files and randomly play audio files at every exercise so your brain gets a variety

**Comment by jithware** [comment]
This can be easily be achieved by other media player apps. Brethap is really not designed to be a media player.
