### ISSUE TITLE
Allow easier switch between techniques

### ISSUE THREAD

**Issue by aquada** [jithware/brethap#74]
I would like to see an easier way to switch between breathing techniques. Currently this is done through preferences, would prefer and upfront option to do this.

Thank you for a great app.

**Comment by jithware** [comment]
To better understand how to implement this, please put together a wireframe for the home screen as documented here: https://github.com/jithware/brethap/issues/56#issuecomment-1241803729. You can use the preferences screen as a starting point. Please include both before (original screen) and after (upfront option) xml files.

**Comment by jithware** [comment]
Added instructions to add/update wireframes see: https://github.com/jithware/brethap/discussions/77

**Comment by jithware** [comment]
See [this](https://github.com/jithware/brethap#running) for preference selection on home screen
