### ISSUE TITLE
Duration should be in multiples of breaths

### ISSUE THREAD

**Issue by wolftune** [jithware/brethap#8]
It's weird to have the duration end in the middle of a breath

Fine to still show the minute:second info, but it should snap to multiples of full breaths, so that it ends at the end of a complete breath.

Could be a slider for just "# of breaths" or "# of rounds" with an integer, just then also *display* the calculated result of how much time that means.

**Comment by jithware** [comment]
In release >= `1.1.0+21`

Allow exhale to complete before shutting down timer. May increase session duration by a few seconds.
