### ISSUE TITLE
[Bug]: application is in german language

### ISSUE THREAD

**Issue by gargamel17** [jithware/brethap#82]
*For questions or comments, please use the [Discussions](https://github.com/jithware/brethap/discussions) section. Please complete the sections below:*

**Describe the bug**
Phone set to french language.
Application is displayed in german.

**To Reproduce**
1. Set your device language to french
2. open application and see it is in german

**Expected behavior**
Application should be in french or let the user choose a different language If french is not available.

**Screenshots**
Device is set to french
![Screenshot_20221129-154929_Paramètres](https://user-images.githubusercontent.com/44755327/204561123-82f7dcaa-633f-4470-8092-81adfb10589f.png)
Application is displayed in german
![Screenshot_20221129-155102_Brethap](https://user-images.githubusercontent.com/44755327/204561513-408f2119-a559-4767-b6cc-e0b774cce09c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Poco F1
 - OS: Android 12
 - Browser firefox
 - Version 107.1

**Additional context**
Add any other context or screenshots about the problem here.

**Comment by jithware** [comment]
Issue is within flutter see: https://github.com/flutter/flutter/issues/100857

**Comment by gargamel17** [comment]
Thanks for the workaround 😄

**Comment by jithware** [comment]
In release >= 1.7.8+78

**Comment by gargamel17** [comment]
> In release >= 1.7.8+78

👍
